<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

	<parent>
		<groupId>de.flapdoodle.wicket10</groupId>
		<artifactId>de.flapdoodle.wicket</artifactId>
		<version>10.2.1-SNAPSHOT</version>
	</parent>

	<modelVersion>4.0.0</modelVersion>
	<artifactId>de.flapdoodle.wicket--examples</artifactId>
	<packaging>war</packaging>
	<name>${project.name} - Examples</name>

	<build>
	<resources>
		  <resource>
			  <filtering>false</filtering>
			  <directory>src/main/resources</directory>
		  </resource>
		  <resource>
			  <filtering>false</filtering>
			  <directory>src/main/java</directory>
			  <includes>
				  <include>**</include>
			  </includes>
			  <excludes>
				  <exclude>**/*.java</exclude>
			  </excludes>
		  </resource>
	  </resources>
	  <testResources>
		  <testResource>
			  <filtering>false</filtering>
			  <directory>src/test/resources</directory>
		  </testResource>
		  <testResource>
			  <filtering>false</filtering>
			  <directory>src/test/java</directory>
			  <includes>
				  <include>**</include>
			  </includes>
			  <excludes>
				  <exclude>**/*.java</exclude>
			  </excludes>
		  </testResource>
	  </testResources>
	  <plugins>
		  <plugin>
			  <groupId>org.apache.maven.plugins</groupId>
			  <artifactId>maven-war-plugin</artifactId>
			  <version>3.4.0</version>
		  </plugin>

<!--		<plugin>-->
<!--			<groupId>org.eclipse.jetty</groupId>-->
<!--			<artifactId>jetty-maven-plugin</artifactId>-->
<!--			<version>${jetty.version}</version>-->
<!--			<configuration>-->
<!--				<systemProperties>-->
<!--					<systemProperty>-->
<!--						<name>maven.project.build.directory.test-classes</name>-->
<!--						<value>${project.build.directory}/test-classes</value>-->
<!--					</systemProperty>-->
<!--				</systemProperties>-->
<!--				<jettyXmls>${project.basedir}/src/test/jetty/jetty.xml,${project.basedir}/src/test/jetty/jetty-ssl.xml,${project.basedir}/src/test/jetty/jetty-http.xml,${project.basedir}/src/test/jetty/jetty-https.xml</jettyXmls>-->
<!--			</configuration>-->
<!--		</plugin>-->
  	</plugins>
  </build>
  
	<dependencies>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>de.flapdoodle.wicket--models</artifactId>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>de.flapdoodle.wicket--atp</artifactId>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>de.flapdoodle.wicket--requests</artifactId>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>de.flapdoodle.wicket--components</artifactId>
		</dependency>
		
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>de.flapdoodle.wicket--debug</artifactId>
		</dependency>

		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>de.flapdoodle.wicket--incubator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.wicket</groupId>
			<artifactId>wicket-extensions</artifactId>
			<scope>runtime</scope>
		</dependency>

		<!--  JETTY DEPENDENCIES FOR TESTING  -->
		<dependency>
			<groupId>org.apache.wicket</groupId>
			<artifactId>wicket-tester</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.jetty</groupId>
			<artifactId>jetty-server</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.jetty.ee10</groupId>
			<artifactId>jetty-ee10-webapp</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.jetty</groupId>
			<artifactId>jetty-jmx</artifactId>
		</dependency>

		<!-- nur falls WebSocket-Unterstützung gebraucht wird -->
		<dependency>
			<groupId>org.eclipse.jetty.ee10.websocket</groupId>
			<artifactId>jetty-ee10-websocket-jakarta-server</artifactId>
		</dependency>

		<!-- WICKET DEPENDENCIES -->
		<dependency>
			<groupId>org.apache.wicket</groupId>
			<artifactId>wicket-native-websocket-javax</artifactId>
		</dependency>
	</dependencies>
  
</project>
